# defaults.py
# By Sebastian Raaphorst, 2020.
#
# Default values for testing and functions.

# Start and stop time of a "day," in minutes.
DEFAULT_START_TIME = 0
DEFAULT_STOP_TIME = 600
DEFAULT_NUM_TIMESLOTS_PER_SITE = DEFAULT_STOP_TIME
DEFAULT_OBS_TIME_LOWER = 15
DEFAULT_OBS_TIME_UPPER = 120

# Default values for execution
DEFAULT_NUM_OBSERVATIONS = 100

# Timeslot length
DEFAULT_TIMESLOT_LENGTH = 1

# DEFAULT_START_TIME = 0
# DEFAULT_STOP_TIME = 100
# DEFAULT_NUM_TIMESLOTS_PER_SITE = DEFAULT_STOP_TIME
# DEFAULT_OBS_TIME_LOWER = 5
# DEFAULT_OBS_TIME_UPPER = 15
#
# # Default values for execution
# DEFAULT_NUM_OBSERVATIONS = 100